### ISSUE TITLE
add temp_calibration to Hue Motion sensors temperature

### ISSUE THREAD

**Issue by Mariusthvdb** [robmarkcole/Hue-sensors-HASS#106]
continuing from: https://community.home-assistant.io/t/hue-motion-sensors-remotes-custom-component/27176/672?u=mariusthvdb

please consider this: 
Hue motion sensors are uncalibrated and are Off/low 1.5 to 2 degrees in general. There are many posts about this on the developers community forum, but all Philips devs are saying is one might have a look in the future.

see: 
https://developers.meethue.com/forum/t/how-to-calibrate-temperature-in-philips-hue-motion-sensor/5564/12

https://developers.meethue.com/forum/t/motion-sensor-temperature-calibration/5512

Which made me wonder if you CC couldn’t build in a variable to be able add to the value the sensors read now.

Ive manually hardcoded it like this now:

```
    elif response["type"] == "ZLLTemperature":
        if response["state"]["temperature"] is not None:
            data = {"temperature": response["state"]["temperature"] / 100.0 + 1.7}
        else:
            data = {"temperature": "No temperature data"}
```

which is probably not the way to do it (had a few rounding issues) but since I did that, all my temp sensors (I use 11) are in much better in sink with my Home thermostats and Indoor climate sensors (that are calibrated)

I would suggest adding a user configurable variable for temp_calibration, either in the config settings or in the CC directly.

I realize this is a Hue issue to solve but until then this would be a tiny and very simple change in the CC, with huge end-user result: correct temp sensors on which we can build are home automations, and great convenience, since we don't have to create extra template sensors to adjust this manually

**Comment by robmarkcole** [comment]
I think this is something we should address at the platform level, rather than ad-hoc

**Comment by yottatsa** [comment]
I think it’s mostly because the sensor is tend to be located high enough to be useful as a PIR sensor.

**Comment by robmarkcole** [comment]
I think the consensus is to close this issue then, and direct users to use one of the existing post-processing tools available in HA. Will leave for timebeing incase anyone else wants to chime in

**Comment by yottatsa** [comment]
Okay, so I've bought a few more of AM2302 (dht) and they all shows the same value. So initially I thought that my first AM2302 was incorrect, now I'm gonna to look onto post-processing tools in HASS. The only problem with calibrating Hue is a native HomeKit support

**Comment by Mariusthvdb** [comment]
fwiw, ive taken the above out of my CC, and use this now, with the same inout_number.temp_calibration for all my sensors:

```
    corridor_motion_sensor_temperature:
      friendly_name: 'Corridor temperature'
      value_template: >
        {{ (state_attr('binary_sensor.corridor_motion_sensor','temperature') +
            states('input_number.temp_calibration')|float)|round(2) }}
      unit_of_measurement: '°C'
      device_class: temperature
```

and have the input_number like this:

```
input_number:
  temp_calibration:
    name: Temp calibration
    initial: 1.7
    min: -2
    max: 2.5
    step: 0.1
    icon: mdi:thermostat
    unit_of_measurement: '°C'
```

though the sensor vary to be off for about 1,5 - 2 degrees, according to my thermostats, they aren't all off by the same, so my general approach isn't anywhere near exact.
A solution should be that we have calibration possibility per sensor...
