### ISSUE TITLE
please add schedule times day and night to the sensors

### ISSUE THREAD

**Issue by Mariusthvdb** [robmarkcole/Hue-sensors-HASS#110]
discussion on community:

https://community.home-assistant.io/t/hue-motion-sensors-remotes-custom-component/27176/712?u=mariusthvdb

would love to have the day and night schedule times, since creating them manually is quite a thing...
created this rest sensor, which I would hope could be added to the CC, to make creation for all sensors automatic (if it would be feasible to find the correct rules, maybe on MotionSensor id? :
full json response  for a relevant rule

`{"name":"MotionSensor 5.night-on","owner":"redacted","created":"2019-01-25T12:39:31","lasttriggered":"2019-01-26T23:59:35","timestriggered":5,"status":"enabled","recycle":true,"conditions":[{"address":"/config/localtime","operator":"in","value":"T22:45:00/T06:30:00"},{"address":"/sensors/5/state/presence","operator":"eq","value":"true"},{"address":"/sensors/5/state/presence","operator":"dx"},{"address":"/sensors/35/state/status","operator":"lt","value":"1"},{"address":"/sensors/6/state/dark","operator":"eq","value":"true"}],"actions":[{"address":"/groups/4/action","method":"PUT","body":{"scene":"qb90i7QlIWkYeG-"}},{"address":"/sensors/35/state","method":"PUT","body":{"status":1}}]}`

```
- platform: rest
  name: Master bedroom schedule rst
  resource: http://192.168.1.212/api/API/rules/20
  method: GET
  value_template: >
    {{ value_json.conditions[0].value }}
```

or if that would fit the CC better, a command_line sensor:

```
- platform: command_line
  name: Control room schedule
  command: curl -X GET http://192.168.1.212/api/API/rules/128
  value_template: >
    {{ value_json.conditions[0].value }}
```

and template these out like:

```
    master_bedroom_schedule_night:
      friendly_name: Master bedroom schedule night
      value_template: >
        {{states('sensor.master_bedroom_schedule_rst')[1:-13]}}
    master_bedroom_schedule_day:
      friendly_name: Master bedroom schedule day
      value_template: >
        {{states('sensor.master_bedroom_schedule_rst')[11:-3]}}
```

to use the in automations like:

```
  - alias: 'Weekend Switch Off Masterbedroom motion sensor'
    id: 'Weekend Switch Off Masterbedroom motion sensor'
#    initial_state: 'on'
    trigger:
      platform: state
      entity_id: binary_sensor.now_master_bedroom_schedule_day
      to: 'on'
#      at: '07:00:00' # the time set in the Hue app, which has only day setting, and doesn't recognize weekend
#      platform: template
#      value_template: >
#        {{now().time().strftime('%H:%M') == states('sensor.master_bedroom_schedule_day')}}
    condition:
      - condition: template
        value_template: >
          {{ is_state ('sensor.activity_selection', 'Slapen')}}
      - condition: template
        value_template: >
          {{is_state('binary_sensor.workday_sensor','off') or 
            is_states('input_boolean.home_mode_vacation','on')}}
    action:
      - service: switch.turn_off
        entity_id: switch.master_bedroom_motion_sensor_switch
```
with:

```
      now_master_bedroom_schedule_day:
        friendly_name: 'Now Master bedroom schedule day'
        entity_id: sensor.time
        value_template: >
          {{now().time().strftime('%H:%M') == states('sensor.master_bedroom_schedule_day')}}
```

thanks for considering!
