### ISSUE TITLE
Platform not found: sensor.hue

### ISSUE THREAD

**Issue by damiano75** [robmarkcole/Hue-sensors-HASS#121]
Hi,
after the update to 0.89 my sensor and my binary_sensor don't work
I have the hue folder under custom_components folder and the code in configuration.yaml is

```
binary_sensor:
  - platoform: hue

sensor:
  - platform: hue
```
but when I check the configuration in HA the message is:

```
Platform not found: sensor.hue
Platform not found: binary_sensor.hue
```
