### ISSUE TITLE
Enhancement Request: Make switches writable

### ISSUE THREAD

**Issue by lweberru** [robmarkcole/Hue-sensors-HASS#153]
Right now, all we get out of this component are are sensory. There is no way to change their state within home assistant. Some example :
* Toggle a dimmer switch or motion detection component on/off
* Press one of the buttons
* Change the light/movement thresholds of motion detection

Thx

**Comment by Kugelfang666** [comment]
Hi 

I use rest commands to switch the Hue motion detectors on/off via Home Assistant and it works rock solid. With regards to the threshold values: I'm sure one can do it in a similar way.

```
switch:
  - platform: command_line
    switches:
      floor_sensor_switch:
        friendly_name: "Sensors Flur"
        command_on: curl -X PUT -d '{"on":true}' "BRIDGEIP/api/APIKEY/sensors/NUMBER/config"
        command_off: curl -X PUT -d '{"on":false}' "BRIDGEIP/api/APIKEY/sensors/NUMBER/config"
        value_template: "{{ is_state('sensor.flur_motion_sensor', 'on') }}"
```
