### ISSUE TITLE
Unable to discover dimmers

### ISSUE THREAD

**Issue by jaruba** [robmarkcole/Hue-sensors-HASS#161]
Got into Home Assistant recently, went through the typical setup and added the Philips Hue integration, it discovered my devices (except dimmers).

Found this repo, downloaded the latest published version, moved the `custom_components` folder to `\\HASSIO\config\custom_components`, edited my `/config/configuration.yaml` to:
```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: https://XXX.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

binary_sensor:
  - platform: huesensor
device_tracker:
  - platform: huesensor
sensor:
  - platform: huesensor
```

restarted Home Assistant, and this is the monumental moment where i'm expecting my dimmers to show in Configuration > Devices, but they're not there.. but I'm rarely the first person to have an issue, so I search the issues and stumble upon this:

https://github.com/robmarkcole/Hue-sensors-HASS/issues/137

following through the pain and suffering of this discussion, I delete the `\\HASSIO\config\custom_components\huesensor\__pycache__` folder, restart again, and reload the Devices page with "Clear cache and hard reload", the dimmers are still not there..

This is the point where I believed I may require assistance, so here we are. I'm stuck in the mud.

Hue Bridge device info:
```
BSB002
by Signify
Firmware: 1935074050
```

HA version: `0.101.3`

Hue-sensors-HASS: `v1.8`
