### ISSUE TITLE
How to setup dimmer?

### ISSUE THREAD

**Issue by inverse** [robmarkcole/Hue-sensors-HASS#167]
I remember previously using this lib before the sensors got integrated into the core.

I've installed the extension via HACS (just installed, is there anything else you need to do? )but I'm unable to see the remotes discovered? what am I missing?

**Comment by inverse** [comment]
@robmarkcole any ideas?

**Comment by robmarkcole** [comment]
They should be discovered, please check your config

**Comment by inverse** [comment]
Will double check. When should each of these be configured? 

```
binary_sensor:
  - platform: huesensor # Motion sensor?
device_tracker:
  - platform: huesensor #?
sensor:
  - platform: huesensor # Remote/Light level? 
```
