### ISSUE TITLE
Feature request: allow toggle

### ISSUE THREAD

**Issue by dm82m** [robmarkcole/Hue-sensors-HASS#198]
Hey,

if I use a remote button for toggline, for example the button should enable/disable a light, then the state is set to "1_click". And on second action, again "1_click" nothing happens, cause the state is already "1_click". Currently I manually set the state with a python script to "0_click" and it works.

But maybe you have an idea about including that into your component.

Best,
Dirk

**Comment by barisahmet** [comment]
I am doing the same workaround in my setup. You have to press button more than one second or script will ignore it. At least can we get a time property of last pressed time? Now it doesnt update `last_updated` if I press a button for a short time.

**Comment by Mincka** [comment]
Same issue here. Either it is not taken in account or I had random ghost double clicks while trying to use the last_update. I manage to make it work by updating a dedicated input_datetime. I compare the last_updated value with the stored one in the input_datime and allow a new action after one second.

Long story short, the main issue here is the fact that it would be best to get **events** for a remote and not use the states. The detection logic of the click should be handled by the component internally and generate events instead of updating the remote state (statuses could be kept to prevent a breaking change).

Hum, while writing this post, I searched again about this issue and found a very easy solution that looks like to work: using the state as a condition, not as a trigger. The trigger is just "triggers on any update" and since the last_updated is updated, it works.

```
- id: '1580671851706'
  alias: Smart Button Push - Julien
  description: ''
  trigger:
  - entity_id: remote.hue_smart_button_1
    platform: state
  condition:
  - condition: state
    entity_id: remote.hue_smart_button_1
    state: 1_click_up
  action:
  - device_id: 0d733138f2bc4d54b2926980627e8d48
    domain: light
    entity_id: light.julien
    type: toggle
```

Credits: https://community.home-assistant.io/t/trigger-on-philips-hue-dimmer-switch-button-press-and-not-state/90598/11
