### ISSUE TITLE
Sensors not working

### ISSUE THREAD

**Issue by gr4z** [robmarkcole/Hue-sensors-HASS#21]
I have hassio v0.60 and upgraded to the latest files. Sensors file as below:

```
 - platform: hue_sensor
  
  - platform: template
    sensors:
      living_room_temperature:
        friendly_name: 'Living Room Temperature'
        entity_id: sensor.living_room_motion_sensor
        value_template: "{{ states.sensor.living_room_motion_sensor.attributes.temperature }}"
        unit_of_measurement: '°C'
      living_room_lux:
        friendly_name: 'Living Room Lux'
        entity_id: sensor.living_room_lux
        value_template: "{{ states.sensor.living_room_motion_sensor.attributes.lux }}"
        unit_of_measurement: 'lux'
      kitchen_temperature:
        friendly_name: 'Kitchen Temperature'
        entity_id: sensor.kitchen_motion_sensor
        value_template: "{{ states.sensor.kitchen_motion_sensor.attributes.temperature }}"
        unit_of_measurement: '°C'
      kitchen_lux:
        friendly_name: 'Kitchen Lux'
        entity_id: sensor.kitchen_motion_sensor
        value_template: "{{ states.sensor.kitchen_motion_sensor.attributes.lux }}"
        unit_of_measurement: 'lux'
```

Once rebooted all sensors fail and error log generated
[home-assistant.log](https://github.com/robmarkcole/Hue-sensors-HASS/files/1571946/home-assistant.log)
