### ISSUE TITLE
How To Use Dimmer Switch?

### ISSUE THREAD

**Issue by rjhilgefort** [robmarkcole/Hue-sensors-HASS#246]
https://github.com/robmarkcole/Hue-remotes-HASS seems to be the only way to work the dimmers, but it's archived. The official integration doesn't have the switches firing anything AFAICT.

I am having a hell of a time figuring out how to get my hue dimmer switch setup. AFAICT, the switch buttons aren't exposed though. I'm thoroughly confused, could anyone point me in the right direction?

**Comment by rudders** [comment]
They are supported natively now.
https://www.home-assistant.io/integrations/hue

**Comment by rjhilgefort** [comment]
Yeah, I had found that page, but I'm still getting used to HA and it wasn't all that helpful. We can definitely close this as it's very unrelated to this repo, but as I close it, I wanted to drop what I figured out to get my switch configured for future Googlers.

I decided to split out all my automatons to individual files and setup my `configuration.yaml` like this:
`configuration.yaml` 
```yaml
automation: !include_dir_list automations
```

`office_dimmer-1-on.yaml`
```yaml
alias: 'Office Dimmer: 1-On'
trigger:
- platform: event
  event_type: hue_event
  event_data:
    entity_id: office_dimmer_switch
    event: 1002
action:
  - entity_id: light.office_lights
    service: light.turn_on
  - entity_id: switch.office_floor_fan
    service: switch.turn_on
```

`office_dimmer-2-plus.yaml`
```yaml
alias: 'Office Dimmer: 2-Plus'
trigger:
- platform: event
  event_type: hue_event
  event_data:
    entity_id: office_dimmer_switch
    event: 2002
condition:  
  condition: state
  entity_id: light.office_lights
  state: 'on'
action:
  service: light.turn_on
  data_template:
    entity_id: light.office_lights
    brightness_pct: >
      {% set brightness_pct = (state_attr('light.office_lights', 'brightness') / 2.55) | int | round(0) %}
      {% set new_brightness = brightness_pct + 10 %}
      {% if new_brightness < 100 %}
        {{ new_brightness }}
      {% else %}
        100
      {% endif %}
```

`office_dimmer-3-minus.yaml`
```yaml
alias: 'Office Dimmer: 3-Minus'
trigger:
- platform: event
  event_type: hue_event
  event_data:
    entity_id: office_dimmer_switch
    event: 3002
condition:  
  condition: state
  entity_id: light.office_lights
  state: 'on'
action:
  service: light.turn_on
  data_template:
    entity_id: light.office_lights
    brightness_pct: >
      {% set brightness_pct = (state_attr('light.office_lights', 'brightness') / 2.55) | int | round(0) %}
      {% set new_brightness = brightness_pct - 10 %}
      {% if new_brightness > 0 %}
        {{ new_brightness }}
      {% else %}
        0
      {% endif %}
```

`office_dimmer-4-off.yaml`
```yaml
alias: 'Office Dimmer: 4-Off'
trigger:
- platform: event
  event_type: hue_event
  event_data:
    entity_id: office_dimmer_switch
    event: 4002
action:
  - entity_id: light.office_lights
    service: light.turn_off
  - entity_id: switch.office_floor_fan
    service: switch.turn_off
```
