### ISSUE TITLE
Hue Dimmer Switch firing events every 5 minutes 

### ISSUE THREAD

**Issue by mmmente** [robmarkcole/Hue-sensors-HASS#55]
I added my Hue accessories (motion sensors, dimmer switches) to hass.io and used node-red to setup some automations with the Hue (4-button) dimmer switch using the events-state node. In detail I want to make use of it as a toggle:

- 1_click --> Kitchen light toggle
- 4_click --> Hallway light toggle
- the 2nd and 3rd button will be used for some other fixtures later.

My problem is that apparently the Hue switch seems to keep sending the last button pressed every 5 minutes as an event and thereby toggling the light every 5 minutes.

Are there any workarounds for this or do I need to change my setup to have separate buttons for on and off? Is this a bug of the implementation?

Thanks!

**Comment by sragas** [comment]
Have the same issue here, but the time is varying betweent a few seconds and a few minutes. It seems like this only happens to the last used dimmer switch. Setup is only in Home Assistant with Template Sensor on last_update and regular autonation. Will also try to investigate this issue deeper.

**Comment by robmarkcole** [comment]
The component does not itself fire events so this almost certainly is an issue with the template/automation

**Comment by mmmente** [comment]
I circumvented the issue by placing a rbe (Report by Exception) node after the Hue dimmer switch and configuring it to "block unless value changes" on the property "msg.data.new_state.attributes.last_updated". Now it works as expected.

**Comment by raoulteeuwen** [comment]
could you try:

```
- alias: hue_remote_TurnOnLightsInLivingRoom
  initial_state: true
  trigger:
     - platform: state
       entity_id: sensor.switch_livingroom
       to: '1_click'
     - platform: state
        entity_id: sensor.switch_livingroom
        state: '1_click_up'
  action:
    - service: light.turn_on
      entity_id: light.livingroom

```

**Comment by CantConAnHonestJohn** [comment]
This really is annoying. I'd really like to help, but how can I debug that? I am having two hue dimmer switches of the same kind. One always works as it should (only fires when pressed), the other one is firing its last state every 5 (or sometimes 10) minutes. I even tried removing it with hue app and resetting but nothing changed.
@mmmente
A rbe node is a mitigation but not a real solution. You turn on your light with your hue switch, turn it off another way. Then how can you turn it on again with your hue switch without having to press two different buttons?

**Comment by mmmente** [comment]
@CantConAnHonestJohn I just live with it and get occasionally yelled at for having a stupid smart home... Did not find a solution, tried to understand the code and still no luck.
I am still hoping

**Comment by f-bader** [comment]
This worked somewhat for me. I switched to zigbee2mqtt in the end
```
- alias: hue_remote_LivingRoom_TurnOnLightsInLivingRoom
  initial_state: true
  trigger:
    - entity_id: sensor.switch_livingroom
      platform: state
  condition:
    - condition: and
      conditions:
      - condition: template
        value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"
      - condition: or
        conditions:
          - condition: state
            entity_id: sensor.switch_livingroom
            state: '1_click'
          - condition: state
            entity_id: sensor.switch_livingroom
            state: '1_click_up'
  action:
    - service: light.turn_on
      entity_id: light.livingroom
```

**Comment by CantConAnHonestJohn** [comment]
@f-bader That is principally what the rbe node does in node-red, so you presumably experience the same problem as @mmmente and me, don't you?
You don't use robs hue sensor at all but only zigbee2mqtt and it still happens. Am I getting this right? Doesn't that mean that the device itself is in fact repeating its last state with zigbee messages? 🤔

**Comment by f-bader** [comment]
Yes that is what node red does. And yes the problem is the same, you can mitigate it a bit by adding click_up.

No with zigbee2mqtt I don't have the problem anymore. The remote itself does not send the event multiple times but only once.
That's one of the reasons why I replaced the plug-in with zigbee2mqtt.

**Comment by j3kestrel** [comment]
I am seeing this issue at 5 minute intervals when my remote is cold enough that the battery isn't reporting a steady 100% charge.  I expect that this can be fixed in the Hue Sensors code but would have to study the event stream/data flow a bit to figure the right place.

**Comment by CantConAnHonestJohn** [comment]
@j3kestrel Fantastic observation 👍! This is a starting point. The one hue remote I'm having this problem with sent the following battery values in its last periodic (5 min) messages: 85, 88, 99, 93, 97, 100 after i took it from the wall to a warmer place. No more message for half an hour until now since it reached 100.
With this new information, could the sensor be fixed, so that changing battery values do not fire the last click event every five minutes? @robmarkcole @yottatsa

**Comment by yottatsa** [comment]
1. Please post a history for this remote. I'm not familiar with states it returns.
2. Have you tried to use [from/to state](https://www.home-assistant.io/docs/automation/trigger/#state-trigger)? cc @raoulteeuwen @f-bader
```
- alias: hue_remote_TurnOnLightsInLivingRoom
  initial_state: true
  trigger:
    - entity_id: sensor.switch_livingroom
      platform: state
      from: 'not_home'  # not sure which value
      to: '1_click'
```

I could ignore battery readings, but this will break battery monitoring if you doesn't press any buttons for a long time. This is because there's only one way to change sensor state and attributes. The only viable option would be splitting it onto multiple devices and/or events.
