### ISSUE TITLE
Remote needs a "standby" state

### ISSUE THREAD

**Issue by mjoshd** [robmarkcole/Hue-sensors-HASS#85]
The remote control works great but really needs one of two things to make it perfect.
Either:
     A) a default state that the remote can return to after the click/hold event has been processed (return to "standby" after some period of time)
or
     B) faster click recognition (it is difficult to get a second click on the same button to register and not have it think I'm trying to do a 'hold')

**Comment by johansmitsnl** [comment]
Did you solve this?

**Comment by yottatsa** [comment]
@johansmitsnl which version of the component do you use? Could you please show the state of the sensor straight from the API before and after clicking the TAP.

**Comment by johansmitsnl** [comment]
@yottatsa here some details:

First click
```json
{
  "state": {
    "buttonevent": 34,
    "lastupdated": "2019-01-28T11:31:36"
  },
  "swupdate": {
    "state": "notupdatable",
    "lastinstall": null
  },
  "config": {
    "on": true
  },
  "name": "Hue TAP Badkamer",
  "type": "ZGPSwitch",
  "modelid": "ZGPSWITCH",
  "manufacturername": "Philips",
  "productname": "Hue tap switch",
  "uniqueid": "00:00:00:00:00:46:69:d2-f2",
  "capabilities": {
    "certified": true
  }
}
```

Second same button:
```json
{
  "state": {
    "buttonevent": 34,
    "lastupdated": "2019-01-28T11:32:13"
  },
  "swupdate": {
    "state": "notupdatable",
    "lastinstall": null
  },
  "config": {
    "on": true
  },
  "name": "Hue TAP Badkamer",
  "type": "ZGPSwitch",
  "modelid": "ZGPSWITCH",
  "manufacturername": "Philips",
  "productname": "Hue tap switch",
  "uniqueid": "00:00:00:00:00:46:69:d2-f2",
  "capabilities": {
    "certified": true
  }
}
```

My automation is like this:
```yaml
- alias: Lights ON
  trigger:
    - platform: state
      entity_id: sensor.hue_tap_badkamer
      to: '1_click'
```

This goes the same for the other HUE dimmer remotes when I only trigger on the `1_click_up`

I use master (6a4b7117b396395bd926c37ff8a5308211faaf6b)

**Comment by johansmitsnl** [comment]
Any updates for this? I do use it correctly or is there another way to trigger on this state?

**Comment by yottatsa** [comment]
Found it. Because the state doesn't change between presses, and the only change is in attributes, you need to use bit different way to trigger:
```
- alias: Lights ON
  trigger:
  - platform: state
    entity_id: sensor.hue_tap_badkamer
  condition:
  - condition: state
    entity_id: sensor.hue_tap_badkamer
    state: '1_click'
```

With this, every event with `'1_click'` state will be picked up.

There's also a bug #55, when the remote is triggering by itself if the attributes are changed. Proposed fix will reset the state to `None` after a while. You could try [this version](https://github.com/yottatsa/Hue-sensors-HASS/blob/attributes/custom_components/sensor/hue.py) after changing the automation.

**Comment by yottatsa** [comment]
The better way to fix it is to emit an event instead of state change.

**Comment by mjoshd** [comment]
Kind of a dirty hack, but what I have been doing is issuing a rest command to manually change the state to ```standby``` after ```1_click_up``` is received and processed in an automation...
```yaml
# rest_commands.yaml
#################
hue_remote_standby: 
  url: http://localhost:8123/api/states/sensor.hue_remote
  method: POST
  headers:
    authorization: !secret hue_remote_standby
  payload: '{"state": "standby"}'
  content_type: application/json
```
```!secret hue_remote_standby``` contains a long lived access token and looks like the following in secrets.yaml where ABCDEFGH is the token generated on the user account page:
```yaml
# secrets.yaml
##########
hue_remote_standby: Bearer ABCDEFGH
```
