### ISSUE TITLE
How to use with multiple Hue bridges?

### ISSUE THREAD

**Issue by recklessnl** [robmarkcole/Hue-sensors-HASS#86]
I have multiple bridges in my house (HASS sees them just fine), how would I configure this?
Is this the recommended way?

  - platform: hue
    ip_address: 192.168.1.69
    token: token1
    ip_address: 192.168.1.70
    token: token2

Not sure if this will work, would be nice to add some information in the readme about multiple bridge IPs.

**Comment by recklessnl** [comment]
Anyone?

**Comment by robmarkcole** [comment]
Please try release 1.0

**Comment by yottatsa** [comment]
For old version it should be:
```
sensor:
  - platform: hue
    ip_address: 192.168.1.69
    token: token1
  - platform: hue
    ip_address: 192.168.1.70
    token: token2
```

For latest just configure this 6 lines from the [README.md](https://github.com/robmarkcole/Hue-sensors-HASS/blob/master/README.md), and ensure that both of your bridges are configured thru the UI.
